language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

script: 'curl -s https://raw.githubusercontent.com/OmniSharp/omnisharp-atom/master/build-package.sh | sh'

git:
  depth: 10
